version: "3.3"
services:
  typhoon-af:
    container_name: typhoon-37-standalone
    image: typhoondata/typhoon-orchestrator_3.7_standalone
    environment:
      - FERNET_KEY=
    ports:
      - "8088:8080"
    volumes:
      - "typhoon_vol:/opt/typhoon/typhoon_project/"
      - "./data_lake:/tmp/data_lake/"

volumes:
  typhoon_vol:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/src
      o: bind
