version: "3.3"
services:
  typhoon-af:
    container_name: typhoon-af
    image: typhoondata/typhoon-orchestrator_airflow1.10:latest
    environment:
      - FERNET_KEY=
    ports:
      - "8088:8080"
    volumes:
      - "typhoon_vol:/opt/typhoon/typhoon_project"
      - "./data_lake:/tmp/data_lake"
      - "./airflow:/usr/local/airflow"

  chown_airflow:
    image: typhoondata/typhoon-orchestrator_airflow1.10:latest
    depends_on:
      - typhoon-af
    restart: "no"
    entrypoint: [ "bash", "chown -R airflow: /usr/local/airflow"]      

volumes:
  typhoon_vol:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/src
      o: bind
