FROM puckel/docker-airflow:1.10.9

ENV AIRFLOW_HOME="/usr/local/airflow"
ENV PROJECT_NAME="typhoon_project"
ENV TYPHOON_HOME="/opt/$PROJECT_NAME/"
ENV PYTHONPATH="$PYTHONPATH:$TYPHOON_HOME"

USER root
RUN set -ex && apt-get update -yqq \
    && apt-get upgrade -yqq \
    && apt-get install -yqq --no-install-recommends \
        libpq-dev
WORKDIR /
COPY . /
RUN pip install -e ./[dev]

RUN cd /opt/ && typhoon init $PROJECT_NAME --deploy-target airflow
WORKDIR $TYPHOON_HOME
