site_name: Typhoon Orchestrator

repo_name: typhoon-orchestrator
repo_url: https://github.com/biellls/typhoon-orchestrator

theme:
    name: 'material'
    palette:
      primary: 'brown'
    logo: 'img/typhoon.png'

google_analytics:
    - 'UA-154972398-1'
    - 'auto'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
