site_name: Typhoon Orchestrator

repo_name: typhoon-orchestrator
repo_url: https://github.com/biellls/typhoon-orchestrator

theme:
    name: 'material'

google_analytics:
    - 'UA-154972398-1'
    - 'auto'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
