

site_name: Typhoon Orchestrator

repo_name: typhoon-orchestrator
repo_url: https://github.com/typhoon-data-org/typhoon-orchestrator

theme:
    name: 'material'
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
    palette:
      primary: 'deep purple'
    logo: 'img/typhoon_solo_inverted2.png'

google_analytics:
    - 'UA-154972398-1'
    - 'auto'

nav:
  - Overview: 'index.md'
  - Getting Started:
    - Installation: 'getting-started/installation.md'
    - Adding connections: 'getting-started/connections.md'
    - Creating your DAG: 'getting-started/creating-a-dag.md'
    - Typhoon Cli: 'getting-started/typhoon-cli.md'
    - Deployment: 'getting-started/deployment.md'
    - Using Components: 'getting-started/using-components.md'
    - UI configurator: 'getting-started/using-component-ui.md'
    - Creating Components: 'getting-started/creating-components.md'
    - New Hooks (connections): 'getting-started/creating-hooks.md'
  - Usage:
    - Dag Context: 'usage/dag-context.md'
    - "!Py & !Multistep": 'usage/py-multistep.md'
    - Task flow control: 'usage/task-flow-control.md'
    - Task testing: 'usage/task-testing.md'
    - Functions: 'usage/functions.md'
    - Transformations: 'usage/transformations.md'
    - Components: 'usage/components.md'
    - Hooks: 'usage/hooks.md'
    - Tempaltes: 'usage/templates.md'
    - Variables: 'usage/variables.md'
  - Example Walkthroughs:
      - Hello World: 'examples/hello-world.md'
      - MySql to Snowflake: 'examples/mysql-to-snowflake.md'
      - Pandas automation: 'examples/automating-pandas.md'
      - Airflow examples: 'examples/airflow-examples.md'
  - Contributing: 'contributing.md'
  - Licence: 'licence.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js