site_name: Typhoon Orchestrator

repo_name: typhoon-orchestrator
repo_url: https://github.com/biellls/typhoon-orchestrator

theme:
    name: 'material'
    palette:
      primary: 'brown'
    logo: 'img/typhoon_solo_inverted2.png'

google_analytics:
    - 'UA-154972398-1'
    - 'auto'

nav:
  - Overview: 'index.md'
  - Getting Started: 'getting-started.md'
  - DAG Development:
    - Tutorial: 'dag-development-tutorial.md'
    - Improving the tutorial DAG: 'dag-development-improving.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
