

site_name: Typhoon Orchestrator

repo_name: typhoon-orchestrator
repo_url: https://github.com/typhoon-data-org/typhoon-orchestrator

theme:
    name: 'material'
    palette:
      primary: 'deep purple'
    logo: 'img/typhoon_solo_inverted2.png'

google_analytics:
    - 'UA-154972398-1'
    - 'auto'

nav:
  - Overview: 'index.md'
  - Getting Started:
    - Installation: 'getting-started.md'
    - Connections: 'connections.md'
    - Creating your DAG: 'creating-a-dag.md'
    - Deployment: 'building-dags.md'
    - Using Components: 'using-components.md'
    - UI configurator: 'using-component-ui.md'
    - Creating Components: 'creating-components.md'
    - Hooks (connections): 'connections.md'
  - Usage:
    - Components: 'components.md'
    - Hooks: 'hooks.md'
  - Example Walkthroughs:
      - Hello World: 'hello-world.md'
      - MySql to Snowflake: 'mysql-to-snowflake.md'
      - Pandas automation: 'automating-pandas.md'
      - Airflow examples: 'airflow-examples.md'
  - Contributing: 'contributing.md'
  - Licence: 'licence.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
