

site_name: TYPHOON

repo_name: typhoon-orchestrator
repo_url: https://github.com/typhoon-data-org/typhoon-orchestrator
edit_uri: ""


theme:
    name: 'material'
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
    palette:
      scheme: typhoon
    logo: 'img/typhoon_flat_icon_white.png'

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js


google_analytics:
    - 'UA-154972398-1'
    - 'auto'

nav:
  - Overview: 'index.md'
  - Getting Started:
    - Installation: 'getting-started/installation.md'
    - Hello World: 'examples/hello-world.md'
    - Typhoon Cli: 'getting-started/typhoon-cli.md'
    - Creating your DAG: 'getting-started/creating-a-dag.md'
    - Adding connections: 'getting-started/connections.md'
    - Deployment: 'getting-started/deployment.md'
    - Using Components: 'getting-started/using-components.md'
    - Component UI: 'getting-started/using-component-ui.md'
    - New Hooks (connections): 'getting-started/creating-hooks.md'
  - Example Walkthroughs:
      - Hello World: 'examples/hello-world.md'
      - MySql to Snowflake: 'examples/mysql-to-snowflake.md'
      - Pandas automation: 'examples/pandas-examples.md'
  - Usage:
    - Dag Context: 'usage/dag-context.md'
    - "!Py & !Multistep": 'usage/py-multistep.md'
    - Task flow control: 'usage/task-flow-control.md'
    - Task testing: 'usage/task-testing.md'
    - Functions: 'usage/functions.md'
    - Transformations: 'usage/transformations.md'
    - Components: 'usage/components.md'
    - Hooks: 'usage/hooks.md'
    - Variables & Templates : 'usage/templates.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

